# Generated by Django 3.1.3 on 2020-11-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0005_auto_20201110_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
    ]
