# Generated by Django 3.1.3 on 2020-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0006_auto_20201110_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Sales Manager', 'Sales Manager'), ('Product Manager', 'Product Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
