# Generated by Django 3.1.3 on 2020-11-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0008_auto_20201116_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
