# Generated by Django 3.0.5 on 2020-11-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0010_remove_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photos_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs308app.Product')),
            ],
        ),
    ]
