# Generated by Django 3.0.5 on 2020-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0011_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_url',
            field=models.CharField(max_length=600),
        ),
    ]
