# Generated by Django 3.1.3 on 2020-11-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0013_auto_20201121_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='user_id',
            new_name='user',
        ),
    ]
