# Generated by Django 3.1.3 on 2020-11-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0014_auto_20201121_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.product'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.product'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.product'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.user'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.product'),
        ),
    ]
