# Generated by Django 3.1.3 on 2020-12-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0021_auto_20201202_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='nickname',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cs308app.user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='cs308app.user'),
            preserve_default=False,
        ),
    ]
