# Generated by Django 3.1.4 on 2020-12-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0022_auto_20201202_2223'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
