# Generated by Django 3.1.4 on 2020-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0024_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='real_stock',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
