# Generated by Django 3.1.4 on 2020-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0025_product_real_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Getting Prepared'), (1, 'On Delivery'), (2, 'Delivered')], default=0),
        ),
    ]
