# Generated by Django 3.1.4 on 2020-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0026_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Getting Prepared'), (1, 'On Delivery'), (2, 'Delivered')], default=0),
        ),
    ]
