# Generated by Django 3.0.5 on 2020-12-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0027_comments_user_id'),
        ('cs308app', '0027_auto_20201220_2000'),
    ]

    operations = [
    ]
