# Generated by Django 3.0.5 on 2020-12-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0028_merge_20201223_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Getting Prepared'), (1, 'On Delivery'), (2, 'Delivered'), (3, 'Cancelled')], default=0),
        ),
        migrations.CreateModel(
            name='OrderAddressChange',
            fields=[
                ('orderadresschange_id', models.AutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cs308app.Address')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cs308app.Order')),
            ],
        ),
    ]
