# Generated by Django 3.0.5 on 2020-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0029_auto_20201223_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_exists',
            field=models.BooleanField(default=True),
        ),
        migrations.RenameField(
            model_name='orderaddresschange',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orderaddresschange',
            old_name='order_id',
            new_name='order',
        ),
    ]
