# Generated by Django 3.1.4 on 2020-12-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0031_auto_20201224_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
