# Generated by Django 3.0.5 on 2021-01-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0033_auto_20201229_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('campaing_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('discount_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaignitems',
            fields=[
                ('campaignitems_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaigninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.CampaignInfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs308app.Product')),
            ],
        ),
    ]
