# Generated by Django 3.0.5 on 2021-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308app', '0035_ordercancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
